# #!Error in this program 
# def getvals():
#     return int(input("Enter a Numerical value :"))

# def calculation(getvals):
#     def square():
#         n=getvals()
#         res=n**2
#         return res
#     return square    


# res=calculation(getvals)   
# result=res
# print(result)



# def getvals():
#     return int(input("Enter a Numerical number :"))

# def outer(getvals):
#     def inner():
#         n=getvals
#         res=n**2
#         return res
#     return inner()


# res=outer(getvals())
# print("Square is = ",res,type(res))

#!
# def getval():
#     return int(input("Enter a Numerical value :"))


# def calculation(kvr):
#     def square():
#         n=kvr()
#         res=n**2
#         return n,res
#     return square

# result=calculation(getval())
# n,squ=result()
# print(n,squ)

# #!
# def getval():
#     return int(input("Enter a Numerical value :"))

# def calculation(kvr):
#     def square():
#         n = kvr()
#         res = n **2
#         return n, res
#     return square

# # Call the returned function to get the values
# result = calculation(getval)
# n, squ = result()  # Notice the extra () to call the function

# print(n, squ)













